version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: ['2181:2181']

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports: ['9092:9092']
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_CREATE_TOPICS: 'input-topic:3:1,output-topic:3:1,goka-output:3:1,group-table:3:1'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  nats-streaming:
    image: nats-streaming:0.12.2
    ports:
      - '4222:4222'
